version: "3.8"
name: aero_radio

services:
  rabbitmq:
    build:
      context: .
      network: host
    container_name: aero-rabbitmq
    network_mode: host
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ./rabbitmq/tls:/etc/rabbitmq/tls:ro
      - ./auth/src:/app/auth/src:ro
